### ISSUE TITLE
Failed to initialize the card (ESP_ERR_INVALID_RESPONSE)

### ISSUE THREAD

**Issue by waqas-subhani** [atomic14/esp32_sdcard_audio#10]
Hi,
I have flash( arduino-wav-sdcard) code at  ESP32 Dev-Kit V1(ESP-WROOM-32), I try same setting for SPI pins mentioned in this code config.h file.
#define PIN_NUM_MISO GPIO_NUM_4
#define PIN_NUM_CLK GPIO_NUM_14   
#define PIN_NUM_MOSI GPIO_NUM_15 
#define PIN_NUM_CS GPIO_NUM_25 
Its not worked for me, giving error
E (324) sdmmc_sd: sdmmc_init_sd_if_cond: send_if_cond (1) returned 0x108
E (325) SDC: Failed to initialize the card (ESP_ERR_INVALID_RESPONSE). Make sure SD card lines have pull-up resistors in place.

I study SPI Pins for ESP-WROOM-32 that are
(VSPI (MISO, CLK, MOSI, CS)=(19, 18, 23, 5))
(HSPI (MISO, CLK, MOSI, CS)=(12, 14, 13, 15))
Also test using VSPI and HSPI pins, also not work for me. I have used Kingston micro SD adopter and try with 32gb  SDHC.

Kindly help me, I do not know what wrong did I do.
Thanks in advance.

**Comment by 7doctor7** [comment]
Hi.
If your adapter has any pull-up resistors or some other parts between SD and ESP pins - then it won't work...
use a simple adapter that is on the main page without any resistors. just add the src code for ESP pull-up pins that you want to use for SD.

**Comment by waqas-subhani** [comment]
Thanks for Reply. It worked for me
