### ISSUE TITLE
Button set-up

### ISSUE THREAD

**Issue by rmond18** [atomic14/esp32_sdcard_audio#2]
Hi, may I ask how did you wire your button to the ESP32?

I tried applying this [example](https://youtu.be/nPMulcBMQ-A?t=45) I saw in youtube:
![image](https://user-images.githubusercontent.com/73434687/118892656-cedd1c80-b933-11eb-860b-f4f88d9cb0cc.png) however I'm still waiting for the resistor I ordered since 7.5k ohm is the lowest resistor value I have at the moment. May I ask if this implementation okay?

Thank you!

**Comment by cgreening** [comment]
One of the nice things about most microcontrollers is that they have built-in pull-up and pull-down resistors that you can enable and disable - so you don't always need to have an external resistor.

In my code I'm using the built-in pull-down resistor:

This is the code using ESP-IDF functions:

```
gpio_set_direction(GPIO_BUTTON, GPIO_MODE_INPUT); 
gpio_set_pull_mode(GPIO_BUTTON, GPIO_PULLDOWN_ONLY);
```

The equivalent code with Arduino functions is:

```
pinMode(GPIO_BUTTON, INPUT_PULLDOWN);
```

You can also use `INPUT_PULLUP` for a pull-up resistor.

If you are using `INPUT_PULLDOWN` (which is what my code is using) then you connect one side of the button to 3v3 and the other side is connected directly to the GPIO pin.

When the button is pushed it will send 3v3 volts to the GPIO pin. When the button is released the internal pull-down resistor will take the GPIO pin to GND.

Looking at the wiring you've got you can remove the resistor and just use `INPUT_PULLDOWN`. You are connecting the button to D1 - so you would need to modify the code in `config.h` to reflect that. Or you can just change your circuit to the same pin that is in `config.h`.
