### ISSUE TITLE
BT sink integration + failed sd card initialization

### ISSUE THREAD

**Issue by rmond18** [atomic14/esp32_sdcard_audio#6]
Hi,

1. Is it possible to integrate the recording feature to a BT sink? 
I'm currently working on integrating this to a [BT sink](https://github.com/tierneytim/btAudio), where instead of the I2S mic, the audio data will be coming from a BT source. 

However I'm still having a hard time on making your code work on my esp32 board, I still got problems with initialization of the sd card. 
![image](https://user-images.githubusercontent.com/73434687/121933799-1e6b0880-cd79-11eb-992f-e7c48eb16d1a.png)
I'm using a microSD card reader module with SanDisk Ultra (16GB) MicroSD HCI formatted as FAT32. 
2. Do you have any idea/tips on how to debug this? 

I tried using the SD card with [other](https://github.com/MhageGH/esp32_SoundRecorder) sound recording code and it worked, still puzzled on why I can't initialize the SD card using your code.

Warm regards,
rmond

**Comment by cgreening** [comment]
Have you updated `config.h` to match the pins you are using for your SDCard?

```
// sdcard
#define PIN_NUM_MISO GPIO_NUM_4
#define PIN_NUM_CLK GPIO_NUM_14
#define PIN_NUM_MOSI GPIO_NUM_15
#define PIN_NUM_CS GPIO_NUM_25
```

**Comment by rmond18** [comment]
Yes, I have updated config.h to match the pins used in my SD card.
I followed these pins for my esp32:
`// sdcard`
`#define PIN_NUM_MISO GPIO_NUM_19//miso`
`#define PIN_NUM_CLK GPIO_NUM_18//clk`
`#define PIN_NUM_MOSI GPIO_NUM_23//mosi`
`#define PIN_NUM_CS GPIO_NUM_2//cs`
![image](https://user-images.githubusercontent.com/73434687/122043771-4e182000-ce0e-11eb-92ab-d899a8d13a63.png)

**Comment by cgreening** [comment]
I think the problem is that you've got pins used for the SD card that are also used for the I2S amplifier.

```
// speaker settings
#define I2S_SPEAKER_SERIAL_CLOCK GPIO_NUM_19
#define I2S_SPEAKER_LEFT_RIGHT_CLOCK GPIO_NUM_27
#define I2S_SPEAKER_SERIAL_DATA GPIO_NUM_18
```

You'll need to move the I2S_SPEAKER_SERIAL_CLOCK and I2S_SPEAKER_SERIAL_DATA to different pins.

**Comment by rmond18** [comment]
I also changed them beforehand and made sure that no pins are used more than once.  I'm actually using UDA1334A decoder instead of an I2S amplifier.
![image](https://user-images.githubusercontent.com/73434687/122067176-f1c0fa80-ce25-11eb-8e51-39d5ef24a866.png)

Is there a difference in using a breakout microsd card adapter (what I'm using) and using a sd card adapter with soldered pins (the one that you used in the video)? I'm thinking if my breakout board is the culprit of the failed sd initialization but it works fine on other code.

**Comment by cgreening** [comment]
It's possible, but I don't see why there would be any difference. SD Cards do seem to be very finickity. There's no reason why you couldn't modify my code to use the standard SD.h which is what is being used in the example you linked to.

Or I would just use the code that works as it looks like it does a very similar thing to this repo.

**Comment by rmond18** [comment]
I tried soldering pins to an sd adapter and used it, finally the SD card worked.
![image](https://user-images.githubusercontent.com/73434687/122126231-091ed880-ce64-11eb-8e48-ce887c071b99.png)

However, the .wav file doesn't have any sound, now I'll try to debug this. Thank you for answering my questions!
![image](https://user-images.githubusercontent.com/73434687/122127675-19d04e00-ce66-11eb-837a-8c6be1821a72.png)


edit: I tried changing the mic L/R from right to left, and it finally worked
![image](https://user-images.githubusercontent.com/73434687/122128960-eee6f980-ce67-11eb-9356-7f1b9fb678a8.png)

Now, I can proceed on trying to integrate this recorded to this [BT sink](https://github.com/tierneytim/btAudio) as an audio source. I would like to ask some tips from you on making the integration possible. How should I change the I2SMEMSSampler so that the data would be coming from a [bt callback](https://github.com/tierneytim/btAudio/blob/dcd4bf5eb592377afc28112ffa10681e0a151716/examples/customCallbacks/customCallbacks.ino#L12) where the variable data16 has the audio data and I need to write this block of data to the SD card but I don't know how.
Thank you again!

**Comment by cgreening** [comment]
That's interesting - what was the SD card adaptor you were using?

To answer your other question - that's a bit outside the scope of this demo repository. I would suggest reading through the current code to see how samples are written to the SD Card. If you have a callback with a set of samples then you should be able to take it from there.

**Comment by rmond18** [comment]
Here is the SD adapter that I soldered that worked:
<img src="https://user-images.githubusercontent.com/73434687/122216475-0614fe00-cedf-11eb-9d45-15d59290d381.png" width="20%" height="20%">

Here is the breakout board that didn't worked:
<img src="https://user-images.githubusercontent.com/73434687/122216551-1d53eb80-cedf-11eb-8d48-06bb5a0d865d.png" width="20%" height="20%">

Some level shifting SD card adapters won't work according to [this](https://www.reddit.com/r/esp32/comments/d71es9/a_breakdown_of_my_experience_trying_to_talk_to_an/).
I'll study your code more on how you write to the SD card, thank you very much again!
