### ISSUE TITLE
Follow up questions (memory allocation + I2S mode)

### ISSUE THREAD

**Issue by rmond18** [atomic14/esp32_sdcard_audio#8]
Hi, it's me again, I have some follow up questions on how you written the samples to the SD Card:

1.1. Why 1024 is multiplied to the size of the memory allocation?
https://github.com/atomic14/esp32_sdcard_audio/blob/9529f60639c22a53948138ab6a0789c70480fd0e/arduino-wav-sdcard/src/main.cpp#L24

1.2. Is it because of the dma buffer length?
https://github.com/atomic14/esp32_sdcard_audio/blob/9529f60639c22a53948138ab6a0789c70480fd0e/arduino-wav-sdcard/src/config.cpp#L12

2. When writing data to SD card, is the mode in i2s config should be I2S_MODE_RX? 
(I'm having trouble since I'm integrating your code on how you written the samples to the SD Card with this [BT sink](https://github.com/tierneytim/btAudio/blob/master/examples/customCallbacks/customCallbacks.ino) where the mode for i2s is TX)

![image](https://user-images.githubusercontent.com/73434687/122649424-6070c180-d160-11eb-932a-6f697b1ca5b7.png)

Thank you very much!

**Comment by cgreening** [comment]
If you are getting your samples from bluetooth and writing them straight to SD Card then you don't need any of the I2S code. `I2S_MODE_RX` is for reading samples from the microphone.
